export const SAGA_USERS='user'
export const SAGA_COMMENTS='comments'
export const SAGA_ALBUMS='albums'
export const SAGA_PHOTOS='photos'
export const SAGA_TODOS='todos'
export const SAGA_POSTS='posts'